---
- hosts: master
  become: yes
  gather_facts: false
  vars_files:
    - ../../vars/host_vars.yml
  tasks:
    - name: Get Join Token
      shell: docker swarm join-token worker -q
      register: join_raw_token

    - name: Set Join Command
      set_fact:
        join_command: "docker swarm join --token {{join_raw_token.stdout_lines[0]}} {{ ctl_host }}:2377"

- hosts: worker
  become: yes
  vars_files:
    - ../../vars/host_vars.yml
  tasks:
    - name: Join Worker to Cluster
      shell: "{{hostvars['ctl1'].join_command}} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
