---
- hosts: storage
  become: yes
  vars_files:
    - ../../secrets/secrets.inc
    - ../../vars/host_vars.yml
  tasks:
    - name: Create Directories for Gitea Stack
      file:
        path: "/srv/doom/gitea"
        state: directory
        mode: '0755'

    - name: Add NFS exports for Gitea Stack
      lineinfile:
        dest: /etc/exports
        line: "/srv/doom/gitea 10.6.0.0/23(rw,sync,no_subtree_check,no_root_squash,no_all_squash)"

    - name: Reload NFS Shares
      command: exportfs -rv

- hosts: master
  become: yes
  vars:
  vars_files:
    - ../../secrets/secrets.inc
    - ../../vars/host_vars.yml
  tasks:
    - name: Create deploy directory
      file:
        path: ~/docker
        state: directory
        mode: '0755'

    - name: Copy Gitea Deployment File
      template:
        src: deploys/gitea.yml.j2
        dest: ~/docker/gitea.yml

    - name: Deploy Gitea service
      shell: docker stack deploy -c ~/docker/gitea.yml gitea

    - name: Remove Gitea deploy file
      file:
        path: ~/docker/gitea.yml
        state: absent
