---
- hosts: storage
  become: yes
  tasks:
    - name: Create Directories for Swarmpit Databases
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /srv/doom/swp/couch
        - /srv/doom/swp/influx

    - name: Add NFS exports for Swarmpit
      lineinfile:
        dest: /etc/exports
        line: "{{ item }}"
      with_items:
        - '/srv/doom/swp/couch 10.6.0.0/23(rw,sync,no_subtree_check,no_root_squash,no_all_squash)'
        - '/srv/doom/swp/influx 10.6.0.0/23(rw,sync,no_subtree_check,no_root_squash,no_all_squash)'

    - name: Reload NFS Shares
      command: exportfs -rv

- hosts: master
  become: yes
  vars_files:
    - ../../vars/host_vars.yml
  tasks:
    - name: Create deploy directory
      file:
        path: ~/docker
        state: directory
        mode: '0755'

    - name: Copy Swarmpit deployment file
      template:
        src: deploys/swarmpit.yml.j2
        dest: ~/docker/swarmpit.yml

    - name: Deploy Swarmpit service
      shell: docker stack deploy -c ~/docker/swarmpit.yml swarmpit

    - name: Remove swarmpit delpoy file
      file:
        state: absent
        path: "~/docker/swarmpit.yml"
