all:
  children:
    vagrant: # Ansible and Vagrant Server
      hosts:
        prodgeek:
          ansible_host: 127.0.0.1
          ansible_connection: local
          ansible_user: monster
          ansible_private_key_file: ~/.ssh/ansible
          ansible_become_pass: "{{ lookup ('env','ANSIBLE_BECOME_PASS')}}"
    
    webservers:
      hosts:
        wordpress1:
          ansible_host: 192.168.1.110
          ansible_user: monster
          ansible_ssh_private_key_file: ~/.ssh/ansible
          ansible_become_pass: "{{ lookup('env', 'ANSIBLE_BECOME_PASS') }}"
          php_webserver_deamon: "nginx"
          php_default_version_debian: "8.1"
        wordpress2:
          ansible_host: 192.168.1.111
          ansible_user: monster # пользователь под которым подключаемся к виртуалке Ansible
          ansible_ssh_private_key_file: ~/.ssh/ansible
          ansible_become_pass: "{{ lookup('env', 'ANSIBLE_BECOME_PASS') }}"
          php_webserver_deamon: "nginx"
          php_default_version_debian: "8.1"

    mariadb_servers:
      hosts:
        mariadb0:
          ansible_host: 192.168.1.112
        mariadb1:
          ansible_host: 192.168.1.113
        mariadb2:
          ansible_host: 192.168.1.114     
     
    monitoring:
      hosts:
        monitoring1:
          ansible_host: 192.168.1.115

    proxy:
      hosts:
        ansible_host:
          ansible_host: 192.168.1.116