all:
  children:
    prodgeek:
      hosts:
        192.168.50.170: # тут должен быть ваш сервер
          ansible_user: monster
          php_webserver_daemon: "nginx"
          php_default_version_debian: "8.1"