---
- hosts: master
  become: yes
  vars_files:
    - ../../secrets/secrets.inc
  tasks:
    - name: Create client key
      command: "openssl genrsa -out /srv/certs/key.pem 4096"

    - name: Create client CSR
      command: "openssl req -subj '/CN=client' -new -key /srv/certs/key.pem -out /srv/certs/client.csr"

    - name: Create extfile
      file:
        state: touch
        path: "/srv/certs/client.cnf"

    - name: Add extendedKeyUsage to extfile
      lineinfile:
        dest: "/srv/certs/client.cnf"
        line: "extendedKeyUsage = clientAuth"

    - name: Create the client certificate
      command: "openssl x509 -req -days 365 -sha256 -in /srv/certs/client.csr -CA /srv/certs/ca.pem -CAkey /srv/certs/ca-key.pem -CAcreateserial -out /srv/certs/cert.pem -extfile /srv/certs/client.cnf -passin pass:{{ sp_pass }}"

    - name: Remove client extfile
      file:
        state: absent
        path: "/srv/certs/client.cnf"

    - name: Remove client CSR
      file:
        state: absent
        path: "/srv/certs/client.csr"
