all:
  children:
    prodgeek:
      hosts:
        192.168.56.20: # тут должен быть ваш сервер
          ansible_user: monster
          ansible_private_key_file: ~/.ssh/ansible
          ansible_become_pass: "{{ lookup ('env','ANSIBLE_BECOME_PASS')}}"
